module.exports ={
  WIDTH:80,
  HEIGHT:46,
  PLAYER_AMOUNT:10,
  MUTATION_RATE:0.3,
  ELITISM_PERCENT:0.1,

  START_HIDDEN_SIZE:0,

  FISH_PROPS : 4,
  FISH_NUM : 30,
  PLAYER_PROPS : 4,
  PLAYER_NUM : 10,
  ITEM_PROPS : 3,
  ITEM_NUM : 10,
  ROCK_PROPS : 3,
  ROCK_NUM : 10,
  BULLET_PROPS : 3,
  BULLET_NUM : 100,
}
