module.exports ={
  WIDTH:80,
  HEIGHT:46,
  PLAYER_AMOUNT:40,
  MUTATION_RATE:0.5,
  ELITISM_PERCENT:0.2,

  START_HIDDEN_SIZE:100,

  MY_PROPS : 10,
  NUMBER_OUTPUT:6,

  FISH_PROPS : 6,
  FISH_NUM : 20,
  PLAYER_PROPS : 6,
  PLAYER_NUM : 10,
  ITEM_PROPS : 3,
  ITEM_NUM : 5,
  ROCK_PROPS : 3,
  ROCK_NUM : 5,
  BULLET_PROPS : 5,
  BULLET_NUM : 20,
}
